### ISSUE TITLE
Instructions are vague.

### ISSUE THREAD

**Issue by ModdingMyMind** [Abhinav1997/speed-up-android#1]
Your instructions don't give precise details on how to properly apply this script when building a custom rom. Could you give some examples? Further more, could you explain how creating a load of random folders will speed up the build? As well as how the build will "detect" it?

**Comment by Abhinav1997** [comment]
This was meant as a simple joke :)

**Comment by ModdingMyMind** [comment]
I already know that. I raised it up as an issue so some idiot didn't bork their system for your retarded joke. ;-)

**Comment by Abhinav1997** [comment]
Fair enough :)

**Comment by Abhinav1997** [comment]
If only, you "knew that" :)

**Comment by ModdingMyMind** [comment]
:-)

**Comment by simplicit** [comment]
What a retarded joke @Abhinav1997. :)

**Comment by Abhinav1997** [comment]
Ikr, feeling so bad :(
